export const quizData = [
	{
		question: "What year was JavaScript launched?",
		a: "1996",
		b: "1995",
		c: "1994",
		d: "none of the above",
		correct: "b",
	},
	{
		question: "What is the syntax for a single-line comment in JavaScript?",
		a: "//",
		b: "/*",
		c: "<!--",
		d: "*/",
		correct: "a",
	},
	{
		question: "Which method is used to add an element to the end of an array?",
		a: "shift()",
		b: "unshift()",
		c: "push()",
		d: "pop()",
		correct: "c",
	},
	{
		question:
			"What is the correct syntax for a function declaration in JavaScript?",
		a: "function myFunction() {}",
		b: "myFunction() {}",
		c: "function = myFunction() {}",
		d: "function: myFunction() {}",
		correct: "a",
	},
	{
		question:
			"What is the output of the following code? console.log(typeof null);",
		a: "null",
		b: "undefined",
		c: "object",
		d: "string",
		correct: "c",
	},
	{
		question: "Which statement is used to exit a loop?",
		a: "continue",
		b: "break",
		c: "return",
		d: "exit",
		correct: "b",
	},
	{
		question: "What is the syntax for a ternary operator in JavaScript?",
		a: "if / else",
		b: "if / else if",
		c: "? / :",
		d: "switch / case",
		correct: "c",
	},
	{
		question: "What is the purpose of the document object in JavaScript?",
		a: "to represent the HTML of a web page",
		b: "to manipulate the HTML of a web page",
		c: "to add styling to a web page",
		d: "none of the above",
		correct: "b",
	},
	{
		question:
			"What is the result of the following code? console.log(5 == '5');",
		a: "true",
		b: "false",
		c: "undefined",
		d: "null",
		correct: "a",
	},
	{
		question: "What is the difference between let and var in JavaScript?",
		a: "let is block-scoped, while var is function-scoped",
		b: "var is block-scoped, while let is function-scoped",
		c: "both let and var are block-scoped",
		d: "both let and var are function-scoped",
		correct: "a",
	},
	{
		question: "What is the purpose of the setTimeout function in JavaScript?",
		a: "to add a delay before executing code",
		b: "to stop executing code after a certain amount of time",
		c: "to repeat code execution at a set interval",
		d: "to execute code synchronously",
		correct: "a",
	},
	{
		question: "Which method is used to return a random number between 0 and 1?",
		a: "Math.random()",
		b: "Math.floor()",
		c: "Math.ceil()",
		d: "Math.round()",
		correct: "a",
	},

	{
		question: "Which of the following is a JavaScript data type?",
		a: "integer",
		b: "string",
		c: "boolean",
		d: "all of the above",
		correct: "b",
	},
	{
		question: "What is the function keyword used for in JavaScript?",
		a: "to declare a variable",
		b: "to declare a function",
		c: "to declare a class",
		d: "none of the above",
		correct: "b",
	},
	{
		question: "What is the name of JavaScript's built-in testing framework?",
		a: "Mocha",
		b: "Jasmine",
		c: "Karma",
		d: "none of the above",
		correct: "b",
	},
	{
		question: "What is a callback function in JavaScript?",
		a: "a function that calls another function",
		b: "a function that is passed as an argument to another function",
		c: "a function that returns a boolean value",
		d: "none of the above",
		correct: "b",
	},
	{
		question: "What does the keyword 'this' refer to in JavaScript?",
		a: "the global object",
		b: "the object that the function is a method of",
		c: "the object that the function is called on",
		d: "none of the above",
		correct: "c",
	},
	{
		question:
			"What is the purpose of the 'use strict' directive in JavaScript?",
		a: "to enable strict mode, which changes certain JavaScript behaviors",
		b: "to disable strict mode, which changes certain JavaScript behaviors",
		c: "to declare a variable",
		d: "none of the above",
		correct: "a",
	},
	{
		question: "What is the difference between 'let' and 'var' in JavaScript?",
		a: "there is no difference",
		b: "'let' is block-scoped, while 'var' is function-scoped",
		c: "'var' is block-scoped, while 'let' is function-scoped",
		d: "none of the above",
		correct: "b",
	},
	{
		question: "What is the difference between '==' and '===' in JavaScript?",
		a: "'==' performs a type coercion, while '===' does not",
		b: "'===' performs a type coercion, while '==' does not",
		c: "both perform type coercion",
		d: "none of the above",
		correct: "a",
	},
	{
		question: "What is the 'typeof' operator used for in JavaScript?",
		a: "to check if a value is null",
		b: "to check if a value is undefined",
		c: "to determine the data type of a value",
		d: "none of the above",
		correct: "c",
	},

	{
		question:
			"Which operator is used to compare two values and their data types?",
		a: "==",
		b: "===",
		c: "!=",
		d: "!==",
		correct: "b",
	},
	{
		question: "What is the typeof operator used for?",
		a: "to check if a variable has been declared",
		b: "to check if a variable has a specific value",
		c: "to check the data type of a value",
		d: "none of the above",
		correct: "c",
	},
	{
		question: "What is the difference between let and var?",
		a: "let is block-scoped and var is function-scoped",
		b: "var is block-scoped and let is function-scoped",
		c: "both let and var are block-scoped",
		d: "none of the above",
		correct: "a",
	},
	{
		question: "What is the difference between const and let?",
		a: "const variables cannot be reassigned, let variables can",
		b: "let variables cannot be reassigned, const variables can",
		c: "both let and const variables can be reassigned",
		d: "none of the above",
		correct: "a",
	},
	{
		question: "What is hoisting in JavaScript?",
		a: "the process of declaring variables before using them",
		b: "the process of moving function declarations to the top of their scope",
		c: "the process of moving variable declarations to the top of their scope",
		d: "none of the above",
		correct: "c",
	},
	{
		question: "What is closure in JavaScript?",
		a: "a way to protect variables from being modified outside their scope",
		b: "the ability of a function to access variables from its outer scope",
		c: "the process of storing functions in variables",
		d: "none of the above",
		correct: "b",
	},
	{
		question: "What is the difference between null and undefined?",
		a: "undefined means the variable has not been assigned a value",
		b: "null means the variable has not been assigned a value",
		c: "null and undefined are the same thing",
		d: "none of the above",
		correct: "a",
	},
	{
		question: "What is a callback function in JavaScript?",
		a: "a function that is called immediately after it is defined",
		b: "a function that is passed as an argument to another function and is executed later",
		c: "a function that is used to create new objects",
		d: "none of the above",
		correct: "b",
	},
	{
		question: "What is a higher-order function in JavaScript?",
		a: "a function that returns another function",
		b: "a function that takes another function as an argument",
		c: "a function that is both a and b",
		d: "none of the above",
		correct: "c",
	},
];

quizData.sort(() => Math.random() - 0.5);



// 
export const quizDataEnglish = [
  {
    question:
      "What is the correct form of the verb 'to be' in the sentence 'I _____ a student'?",
    a: "is",
    b: "am",
    c: "are",
    d: "be",
    correct: "b",
  },
  {
    question: "Which word is a pronoun?",
    a: "book",
    b: "table",
    c: "he",
    d: "run",
    correct: "c",
  },
  {
    question: "What is the opposite of the word 'hot'?",
    a: "big",
    b: "small",
    c: "cold",
    d: "fast",
    correct: "c",
  },
  {
    question: "Which sentence is written correctly?",
    a: "She go to the store.",
    b: "He am playing soccer.",
    c: "I is happy.",
    d: "They are my friends.",
    correct: "d",
  },
  {
    question: "What is the plural form of the word 'cat'?",
    a: "cats",
    b: "caties",
    c: "cates",
    d: "catz",
    correct: "a",
  },
  {
    question: "Which word is a preposition?",
    a: "play",
    b: "with",
    c: "jump",
    d: "good",
    correct: "b",
  },
  {
    question: "What is the past tense of the verb 'eat'?",
    a: "eated",
    b: "ate",
    c: "eat",
    d: "eaten",
    correct: "b",
  },
  {
    question: "Which sentence is a question?",
    a: "I like ice cream.",
    b: "They are going to the park.",
    c: "Do you want some juice?",
    d: "The dog is sleeping.",
    correct: "c",
  },
  {
    question: "What is the plural form of the word 'child'?",
    a: "childs",
    b: "childes",
    c: "children",
    d: "childz",
    correct: "c",
  },
  {
    question:
      "What is the correct spelling of the color that is a mixture of blue and yellow?",
    a: "grean",
    b: "yelow",
    c: "green",
    d: "bluy",
    correct: "c",
  },
  {
    question: "Which word is an adjective?",
    a: "run",
    b: "quickly",
    c: "happy",
    d: "outside",
    correct: "c",
  },
  {
    question: "Which sentence is written correctly?",
    a: "I doesn't like bananas.",
    b: "He have two cats.",
    c: "She is playing soccer.",
    d: "We are go to the park.",
    correct: "c",
  },
  {
    question: "What is the opposite of the word 'big'?",
    a: "small",
    b: "tall",
    c: "fast",
    d: "long",
    correct: "a",
  },
  {
    question: "Which word is a conjunction?",
    a: "and",
    b: "sing",
    c: "ball",
    d: "good",
    correct: "a",
  },
  {
    question: "What is the present participle of the verb 'run'?",
    a: "running",
    b: "runned",
    c: "run",
    d: "runs",
    correct: "a",
  },
  {
    question: "Which sentence is a command?",
    a: "You are my friend.",
    b: "Go to bed!",
    c: "She is reading a book.",
    d: "We went to the park.",
    correct: "b",
  },
  {
    question: "What is the plural form of the word 'mouse'?",
    a: "mouses",
    b: "mices",
    c: "mice",
    d: "mices",
    correct: "c",
  },
];

quizDataEnglish.sort(() => Math.random() - 0.5);